% Input: base workspace vars mode_id_sim, fault_id_sim, sim_params
% Output: models/dc_psv_system.slx generated and saved
% Pos: scripts/build_dc_psv_system.m

function model_path = build_dc_psv_system()
    root_dir = fileparts(fileparts(mfilename('fullpath')));
    model_name = 'dc_psv_system';
    models_dir = fullfile(root_dir, 'models');
    model_path = fullfile(models_dir, [model_name '.slx']);

    if ~exist(models_dir, 'dir')
        mkdir(models_dir);
    end

    if bdIsLoaded(model_name)
        close_system(model_name, 0);
    end

    new_system(model_name);
    open_system(model_name);

    set_param(model_name, 'Solver', 'ode4');
    set_param(model_name, 'FixedStep', '5e-5');
    set_param(model_name, 'StopTime', '1.0');

    add_block('simulink/Sources/Clock', [model_name '/Clock'], ...
        'Position', [60 90 90 120]);
    add_block('simulink/Sources/Constant', [model_name '/Mode_ID'], ...
        'Value', 'mode_id_sim', 'Position', [60 170 120 200]);
    add_block('simulink/Sources/Constant', [model_name '/Fault_ID'], ...
        'Value', 'fault_id_sim', 'Position', [60 240 120 270]);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [model_name '/DC_Bus_Model'], 'Position', [220 90 460 290]);

    fcn_script = [ ...
        "function [vdc,idc,v_pos_gnd,v_neg_gnd] = fcn(t,mode_id,fault_id)" newline ...
        "Vnom = 1500;" newline ...
        "load_kw = [3270, 6270, 2170, 3620];" newline ...
        "drop_v = [0, 18, -8, 5];" newline ...
        "if mode_id < 1 || mode_id > 4" newline ...
        "    mode_id = 1;" newline ...
        "end" newline ...
        "if t < 0.5" newline ...
        "    active_mode = 1;" newline ...
        "else" newline ...
        "    active_mode = mode_id;" newline ...
        "end" newline ...
        "startup_gain = 1 - exp(-t/0.03);" newline ...
        "v_target = Vnom - drop_v(active_mode);" newline ...
        "mode_transient = 0;" newline ...
        "if active_mode ~= 1 && t >= 0.5" newline ...
        "    mode_transient = -22 * exp(-(t - 0.5) / 0.05);" newline ...
        "end" newline ...
        "vdc = v_target * startup_gain + mode_transient;" newline ...
        "fault_on = (t >= 0.6) && (t <= 0.65);" newline ...
        "if fault_on" newline ...
        "    if fault_id == 1" newline ...
        "        vdc = 0.30 * vdc;" newline ...
        "    end" newline ...
        "end" newline ...
        "if vdc < 5" newline ...
        "    vdc = 5;" newline ...
        "end" newline ...
        "v_pos_gnd = 0.5 * vdc;" newline ...
        "v_neg_gnd = -0.5 * vdc;" newline ...
        "if fault_on" newline ...
        "    if fault_id == 2" newline ...
        "        v_pos_gnd = 0;" newline ...
        "        v_neg_gnd = -vdc;" newline ...
        "    elseif fault_id == 3" newline ...
        "        v_neg_gnd = 0;" newline ...
        "        v_pos_gnd = vdc;" newline ...
        "    end" newline ...
        "end" newline ...
        "idc = (load_kw(active_mode) * 1000) / vdc;" newline ...
        "if fault_on && fault_id == 1" newline ...
        "    idc = 3.0 * idc;" newline ...
        "end" newline ...
        "end" ...
    ];

    rt = sfroot;
    chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', [model_name '/DC_Bus_Model']);
    if isempty(chart)
        error('Failed to access MATLAB Function chart for script injection.');
    end
    chart.Script = char(fcn_script);

    add_block('simulink/Sinks/To Workspace', [model_name '/Vdc_ToWorkspace'], ...
        'VariableName', 'Vdc', 'SaveFormat', 'Timeseries', ...
        'Position', [560 95 660 125]);
    add_block('simulink/Sinks/To Workspace', [model_name '/Idc_ToWorkspace'], ...
        'VariableName', 'Idc', 'SaveFormat', 'Timeseries', ...
        'Position', [560 145 660 175]);
    add_block('simulink/Sinks/To Workspace', [model_name '/V_pos_ToWorkspace'], ...
        'VariableName', 'V_pos_gnd', 'SaveFormat', 'Timeseries', ...
        'Position', [560 195 660 225]);
    add_block('simulink/Sinks/To Workspace', [model_name '/V_neg_ToWorkspace'], ...
        'VariableName', 'V_neg_gnd', 'SaveFormat', 'Timeseries', ...
        'Position', [560 245 660 275]);

    add_line(model_name, 'Clock/1', 'DC_Bus_Model/1', 'autorouting', 'smart');
    add_line(model_name, 'Mode_ID/1', 'DC_Bus_Model/2', 'autorouting', 'smart');
    add_line(model_name, 'Fault_ID/1', 'DC_Bus_Model/3', 'autorouting', 'smart');

    add_line(model_name, 'DC_Bus_Model/1', 'Vdc_ToWorkspace/1', 'autorouting', 'smart');
    add_line(model_name, 'DC_Bus_Model/2', 'Idc_ToWorkspace/1', 'autorouting', 'smart');
    add_line(model_name, 'DC_Bus_Model/3', 'V_pos_ToWorkspace/1', 'autorouting', 'smart');
    add_line(model_name, 'DC_Bus_Model/4', 'V_neg_ToWorkspace/1', 'autorouting', 'smart');

    save_system(model_name, model_path);
    close_system(model_name, 0);
end
